### PR TITLE
CRW-1235 move to python 3.8 w/ new lang server deps

### PR DESCRIPTION
**Pull request by nickboldt**
WIP: CRW-1235 possible solution to move to python 3.8

Change-Id: I9bae3e2bf3037f13af1d96fcf8413a897d606639
Signed-off-by: nickboldt <nboldt@redhat.com>

### CODE REVIEW

**Comment by ericwill** [comment]
The extension needs to be updated to fix CRW-1235. So this is the first step but it won't solve that issue.

**Review by ericwill — APPROVED** [review]

**Comment by ericwill** [comment]
In conjunction with https://github.com/redhat-developer/codeready-workspaces-deprecated/pull/64, this PR should be enough to do the 3.8 upgrade.

**Comment by nickboldt** [comment]
[crw lang server dep builder build #9](https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/CRW_CI/job/crw-deprecated_2.6/9/) buildng now to pick up changes in [PR#64](https://github.com/redhat-developer/codeready-workspaces-deprecated/pull/64). When done, we can triggger the [plugins-and-stacks sync job](https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/CRW_CI/job/crw-plugins-and-stacks_2.6/build?delay=0sec) using these two repos:

```
codeready-workspaces-plugin-java8-openj9, 
codeready-workspaces-plugin-java8, 
```

**Comment by nickboldt** [comment]
rebuilding images finally in https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/CRW_CI/job/crw-plugins-and-stacks_2.6/26/parameters/ (java images = python sidecars)

**Pull request merged**
