### PR TITLE
CRW-1594 convert scratch image to...

### PR DESCRIPTION
**Pull request by nickboldt**
### What does this PR do?

CRW-1594 convert scratch image to ubi8-minimal image (like jwtproxy) and apply jwtproxy's bootstrap/vendoring solution too

Change-Id: I6887641f1934ef8cf0967eb17c0d085e7f702175
Signed-off-by: nickboldt <nboldt@redhat.com>

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
N/A (or see commit message above for issue number)

### How to test this PR?
N/A

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works, if one exists](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections What issues does this PR fix or reference and How to test this PR completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by benoitf** [comment]
It looks like opposite way to move away from scratch images to go to containers image

**Comment by nickboldt** [comment]
requires https://gitlab.cee.redhat.com/codeready-workspaces/crw-jenkins/-/merge_requests/506

fixes https://issues.redhat.com/browse/CRW-1594 and https://issues.redhat.com/browse/RHDEVDOCS-2852

**Comment by nickboldt** [comment]
If you can figure out how to copy /bin/sleep into scratch image and have it work w/ Openshift... I'm all ears. 

I tried doing so in https://github.com/eclipse-che/che-machine-exec/commit/2f340f4ecf0c9b82694f1aa2c0b470d13b0877e2 but it didn't work - see https://issues.redhat.com/browse/CRW-1594?focusedCommentId=15924623&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15924623

So I figured if we can't run sleep in a scratch, we might as well move the image to ubi8-minimal so ALL the CRW containers are UBI8 based (except operator metadata, which MUST be an archless scratch image)

**Comment by nickboldt** [comment]
PR is now out dated after che-incubator/kubernetes-image-puller@ca8388e merged in upstream.

**Pull request closed without merging**
