### PR TITLE
Switch dashboard to yarn 1

### PR DESCRIPTION
**Pull request by sleshchenko**
Since IBM Z does not support yarn 2 yet, we're stuck with yarn 1.
Not to move upstream back, we're switching to yarn 1 during source sync.

This PR is WIP due the following TODOs:
- [x] load node_modules and everything else needed (node cache, I don't know) to lookaside cache;
- [x] adjust Dockerfile to use archive from lookaside cache;

Thanks @akurinnoy for the idea and help on preparing all the needed commands.

### CODE REVIEW

**Comment by nickboldt** [comment]
Can you also update https://github.com/redhat-developer/codeready-workspaces-images/blob/crw-2-rhel-8/codeready-workspaces-dashboard/get-sources-jenkins.sh#L48-L50 if applicable so that we're collecting from the vendor folder instead of the .yarn folder?

**Comment by nickboldt** [comment]
Does this line need to change? 

```
   `# insert logic to unpack asset-yarn-cache.tgz into /dashboard/.yarn/cache` \    
   -e "/RUN \/dashboard\/.yarn\/releases\/yarn-\*.cjs install/i COPY asset-yarn-cache.tgz /tmp/\nRUN tar xzf /tmp/asset-yarn-cache.tgz &amp;&amp; rm -f /tmp/asset-yarn-cache.tgz" \<br class="Apple-interchange-newline">
```
-- https://github.com/redhat-developer/codeready-workspaces-images/pull/38/files#diff-cc37a4dd669a3e537acff822a5af8717b80aee6d1558a9f94177b73b764d4720R104

**Comment by nickboldt** [comment]
Seems this PR now includes merged changes from https://github.com/redhat-developer/codeready-workspaces-images/pull/41

**Review by nickboldt — APPROVED** [review]
With Josh's updates, I think this might be ready to merge and try it out.

**Comment by sleshchenko** [comment]
We're not sure it's going to work since nobody install yarn v1, but merging it after Nick approval, and we'll see for sure =)

**Pull request merged**
